# base image
FROM python:3.9-slim

WORKDIR /app

COPY . /app

# below command is used to install Flask framework in the container
RUN pip install --no-cache-dir -r requirements.txt

# adding non-root user 
RUN useradd -m nonrootuser

USER nonrootuser

EXPOSE 9000

ENV FLASK_APP=app.py

#Run the application 
CMD ["flask", "run", "--host=0.0.0.0", "--port=9000"]
